from base import *
bread=item(
    item_id='bread',
    texture='bread',
    name='Bread'
)
iron=item(
    item_id='iron',
    texture='iron',
    name='Iron'
)
wood=item(
    item_id='wood',
    texture='wood',
    name='Wood'
)
meat=item(
    item_id='meat',
    texture='meat',
    name='Meat'
)
leaf=item(
    item_id='leaf',
    texture='leaf',
    name='Leaf'
)
energy=item(
    item_id='energy',
    texture='lightning',
    name='Energy'
)
dark_orb=item(
    item_id='dark_orb',
    texture='dark_orb',
    name='Mysterious'
)
water=item(
    item_id='water',
    name='Water',
    texture='water'
)
scale=item(
    item_id='scale',
    name='Scale',
    texture='scale'
)
wool=item(
    item_id='wool',
    name='Wool',
    texture='wool'
    )
marble=item(
    item_id='marble',
    name='Marble',
    texture='marble'
    )