from base import *
farmer=mob(
    ai=ai(is_hostile=True,min_distance=0,max_distance=70,speed=1),
    health=1,
    loot=loot_table(items={'bread':1}),
    mob_type='farmer',
    texture='farmer',
    death_sound='im_dead'
)
knight=mob(
    ai=ai(is_hostile=True,max_distance=50,speed=1.5),
    health=3,
    loot=loot_table(items={'iron':1}),
    texture='knight',
    damage=2,
    xp=4,
    mob_type='knight',
    hit_sound='armor',
    death_sound='knight_death'
)
wanderer=mob(
    ai=ai(is_hostile=True,max_distance=40,speed=2),
    health=5,
    loot=loot_table(items={'iron':2,'bread':4,'wood':1},drops=2,limited_items=True),
    texture='wanderer',
    damage=3,
    xp=7,
    mob_type='wanderer',
    hit_sound='ghastly',
    death_sound='ghastly'
)
tree_man=mob(
    ai=ai(is_hostile=True,max_distance=20,speed=1.5),
    health=10,
    loot=loot_table(items={'wood':6,'leaf':1}),
    texture='tree_man',
    damage=5,
    xp=12,
    mob_type='tree_man',
    hit_sound='hit',
    death_sound='tree_chopped'
)
caveman=mob(
    ai=ai(is_hostile=True,max_distance=30,speed=1),
    health=6,
    loot=loot_table(items={'meat':1,'void':2},drops=2,limited_items=True),
    texture='caveman',
    damage=3,
    xp=7,
    mob_type='caveman',
    hit_sound='splat',
    death_sound='cave_death'
)
energen=mob(
    ai=ai(is_hostile=True,max_distance=15,speed=1.5),
    health=12,
    loot=loot_table(items={'energy':1,'void':1}),
    texture='energen',
    damage=2,
    xp=19,
    mob_type='energen'
)
dark_wanderer=mob(
    ai=ai(is_hostile=True,max_distance=25,speed=2.25),
    health=35,
    loot=loot_table(items={'energy':2,'iron':1,'void':3,'dark_orb':1},drops=2,limited_items=True),
    texture='wanderer_dark',
    damage=5,
    xp=42,
    mob_type='dark_wanderer',
    hit_sound='ghastly',
    death_sound='sheep_death'
)
ogre=mob(
    ai=ai(is_hostile=True,max_distance=0,speed=0.5),
    health=25,
    loot=loot_table(items={'meat':2,'bread':1,'void':1},drops=2),
    texture='ogre',
    damage=9,
    xp=25,
    mob_type='ogre',
    death_sound='splat',
    hit_sound='burp'
)
evil_orb=projectile(
    ai=forward(5,is_hostile=True),
    health=25,
    loot=loot_table(items={'dark_orb':1,'energy':3,'void':10},drops=3),
    texture='evil_orb',
    damage=15,
    mob_type='evil_orb'
)
wraith=mob(
    ai=ai(is_hostile=True,max_distance=35,speed=2.4),
    health=100,
    loot=loot_table(items={'dark_orb':1,'void':100},drops=3),
    texture='wanderer_wraith',
    shape='wanderer',
    damage=12,
    xp=75,
    mob_type='wraith',
    ranged={
        'projectile':"""projectile(
ai=forward(5,is_hostile=True),
health=25,
loot=loot_table(items={'dark_orb':1,'energy':3,'void':10},drops=3),
texture='evil_orb',
damage=15,
mob_type='evil_orb'
)""",
        'fire_rate':0.25
    },
    hit_sound='ghastly',
    death_sound='wraith_death'
)
snake=mob(
    ai=ai(is_hostile=True,max_distance=player.width//2-1,speed=2.5),
    health=50,
    loot=loot_table(items={'meat':4,'energy':1,'scale':2},drops=2),
    texture='snake',
    damage=9,
    xp=63,
    mob_type='snake',
    death_sound='wraith_death',
    hit_sound='shield'
)
large_tree_man=mob(
    ai=ai(is_hostile=True,max_distance=1,speed=1.25),
    health=35,
    loot=loot_table(items={'wood':4,'leaf':1},drops=3),
    texture='tree_man_xl',
    damage=10,
    xp=50,
    mob_type='large_tree_man',
    hit_sound='hit',
    death_sound='tree_chopped'
)
sheep=mob(
    ai=ai(is_hostile=False,max_distance=1000,min_distance=800,speed=0.5),
    health=15,
    loot=loot_table(items={'meat':4,'void':1,'wool':2},drops=3),
    texture='shep_',
    xp=5,
    mob_type='sheep',
    hit_sound='ghastly',
    death_sound='sheep_death'
)
farmer_armored=mob(
    ai=ai(is_hostile=True,min_distance=0,max_distance=70,speed=1),
    health=20,
    loot=loot_table(items={'bread':1},drops=2),
    mob_type='farmer_armored',
    texture='farmored',
    xp=15,
    damage=7,
    hit_sound='hit',
    death_sound='splat'
)
haunter=mob(
    ai=ai(is_hostile=True,max_distance=15,speed=2.5),
    health=200,
    loot=loot_table(items={'dark_orb':1}),
    texture='haunter',
    damage=15,
    xp=100,
    mob_type='haunter',
    hit_sound='ghastly',
    death_sound='sheep_death'
)
hot_rock=mob(
    ai=ai_line(is_hostile=True,speed=3.5),
    health=50,
    loot=loot_table(items={'marble':1},drops=3),
    texture='hot_rock',
    shape='hot_rock_mask',
    damage=25,
    xp=100,
    mob_type='hot_rock',
    hit_sound='shield',
    death_sound='hit'
)
crying_cherub=mob(
    ai=creep_ai(is_hostile=True,distance=50,speed=2),
    health=100,
    loot=loot_table(items={'marble':1}),
    texture='cherub',
    damage=10,
    xp=70,
    mob_type='crying_cherub',
    hit_sound='hit',
    death_sound='wraith_death'
)
sheep_winter=mob(
    ai=sneak_ai(is_hostile=True,distance=2000,speed=0.75),
    health=50,
    loot=loot_table(items={'meat':4,'void':1,'wool':5},drops=4),
    texture='shep_winter',
    xp=25,
    mob_type='sheep_winter',
    hit_sound='hit',
    death_sound='sheep_death'
)
mountain_man=mob(
    ai=ai(is_hostile=True,max_distance=30,speed=1.2),
    health=60,
    loot=loot_table(items={'meat':1,'scale':2},drops=2),
    texture='mountain_man',
    damage=9,
    xp=70,
    mob_type='mountain_man',
    hit_sound='splat',
    death_sound='cave_death'
)
dying_cherub=mob(
    ai=ai(is_hostile=True,max_distance=50,speed=2),
    health=100,
    loot=loot_table(items={'marble':1,'ice_shard':2},drops=2),
    texture='dying_cherub',
    damage=10,
    xp=85,
    mob_type='dying_cherub',
    hit_sound='hit',
    death_sound='wraith_death'
)
bare_man=mob(
    ai=ai(is_hostile=True,max_distance=30,speed=1.5),
    health=50,
    loot=loot_table(items={'meat':1},drops=3),
    texture='base_muscular',
    damage=12,
    xp=90,
    mob_type='bare_man',
    hit_sound='burp',
    death_sound='cave_death'
)
stone_hound=mob(
    ai=veep_ai(is_hostile=True,distance=30,speed=2.5),
    health=75,
    loot=loot_table(items={'marble':2,'ice_shard':1},drops=2,limited_items=True),
    texture='stonehound',
    damage=12,
    xp=110,
    mob_type='stone_hound',
    hit_sound='hit',
    death_sound='aether_hound_death'
)
dead_cherub=mob(
    ai=ai(is_hostile=True,max_distance=50,speed=2.3),
    health=130,
    loot=loot_table(items={'marble':1,'lava':2},drops=2),
    texture='dead_cherub',
    damage=13,
    xp=115,
    mob_type='dead_cherub',
    hit_sound='hit',
    death_sound='lava_angel_death'
)
lava_hound=mob(
    ai=veep_ai(is_hostile=True,distance=40,speed=3),
    health=100,
    loot=loot_table(items={'marble':2,'lava':1},drops=2,limited_items=True),
    texture='lava_hound',
    damage=15,
    xp=170,
    mob_type='lava_hound',
    hit_sound='hit',
    death_sound='aether_hound_death'
)
ogre_v_5487=mob(
    ai=ai(is_hostile=True,max_distance=0,speed=0.5),
    health=25,
    loot=loot_table(items={'meat':20,'bread':5,'void':10,'lava':1},drops=12),
    texture='secret_ogre_skin_v_5487',
    shape='ogre',
    damage=9,
    xp=59,
    mob_type='ogre',
    death_sound='im_not_dead',
    hit_sound='burp'
)
boss_test=mob(
    ai=creep_ai(is_hostile=True,distance=50,speed=2),
    health=1000,
    loot=loot_table(items={'dark_orb':1},drops=10),
    texture='wanderer_wraith',
    damage=50,
    xp=250,
    mob_type='boss_test'
)