from base import *
upgrades=[
    upgrade(texture='dark_orb',items={'dark_orb':10},upgrade_id='power',name='Increase Power',level=16,max=1,upgrade=power_upgrade(1),name_color=(255,0,255)),
    upgrade(items={'iron':10,'wood':4},level=5,upgrade_id='shield_upgrade',name='Shield',max=1,upgrade=lambda:setattr(player, 'can_shield', True),texture='shield_upgrade'),
    upgrade(texture='xp_boost',items={'wool':5,'scale':2},upgrade_id='armor_i',name='Upgrade Armor',level=10,max=10,show_uses=True,upgrade=armor_upgrade(1)),
    upgrade(texture='xp_boost',items={'scale':5,'dark_orb':1},upgrade_id='armor_ii',name='Upgrade Armor',level=15,max=15,show_uses=True,upgrade=armor_upgrade(2)),
    upgrade(texture='xp_boost',items={'scale':50,'dark_orb':10},upgrade_id='armor_iii',name='Upgrade Armor',level=19,max=1,show_uses=True,upgrade=armor_upgrade(10)),
    upgrade(texture='attack',upgrade_id='range_5',upgrade=range_upgrade(5),name='Range Upgrade',max=10,show_uses=True,items={'iron':1}),
    upgrade(texture='attack',upgrade_id='range_5_ii',upgrade=range_upgrade(5),name='Range Upgrade II',max=5,show_uses=True,items={'iron':2},level=4),
    upgrade(texture='attack',upgrade_id='range_5_iii',upgrade=range_upgrade(5),name='Range Upgrade III',max=5,show_uses=True,items={'iron':1,'wood':1},level=7),
    upgrade(texture='attack',upgrade_id='range_5_iv',upgrade=range_upgrade(5),name='Range Upgrade IV',max=10,show_uses=True,items={'iron':1,'energy':1},level=14),
    upgrade(level=2,texture='damage_upgrade',upgrade_id='damage_1',upgrade=damage_upgrade(1),name='Damage Upgrade',max=5,show_uses=True,items={'iron':2}),
    upgrade(level=7,texture='damage_upgrade',upgrade_id='damage_1_ii',upgrade=damage_upgrade(1),name='Damage Upgrade II',max=5,show_uses=True,items={'iron':3,'wood':1}),
    upgrade(level=14,texture='damage_upgrade',upgrade_id='damage_2',upgrade=damage_upgrade(2),name='Damage Upgrade III',max=10,show_uses=True,items={'energy':10}),
    upgrade(upgrade=heal_upgrade(2),texture='heart',name='Heal (2)'),
    upgrade(upgrade=heal_upgrade(5),texture='heart',name='Heal (5)',items={'meat':1},level=8),
    upgrade(items={'bread':2,'leaf':1},upgrade=jump_upgrade(10),name='Jump Upgrade',level=3,max=5,show_uses=True,texture='jump_upgrade'),
    upgrade(texture='shield_upgrade',items={'wood':1},upgrade_id='knock_1',name='Knockback Upgrade',level=6,max=5,show_uses=True,upgrade=knock_upgrade(1)),
    upgrade(texture='shield_upgrade',items={'wood':3,'iron':1},upgrade_id='knock_2',name='Knockback Upgrade II',level=9,max=5,show_uses=True,upgrade=knock_upgrade(2)),
    upgrade(texture='attack',items={'iron':10,'energy':1},upgrade_id='strike_i',name='Strike Upgrade',level=10,max=10,show_uses=True,upgrade=knock_upgrade(0.5)),
    upgrade(texture='attack',items={'dark_orb':1,'iron':50},upgrade_id='strike_ii',name='Strike Upgrade',level=18,max=35,show_uses=True,upgrade=knock_upgrade(1)),
    upgrade(texture='gold_heart',items={'bread':10},upgrade_id='hp_1',name='Health Upgrade',level=6,max=5,show_uses=True,upgrade=multiple(max_hp_upgrade(1),heal_upgrade(1))),
    upgrade(texture='gold_heart',items={'bread':50,'meat':5},upgrade_id='hp_2',name='Health Upgrade',level=8,max=5,show_uses=True,upgrade=multiple(max_hp_upgrade(2),heal_upgrade(1))),
    upgrade(texture='gold_heart',items={'energy':1,'meat':25},upgrade_id='hp_3',name='Health Upgrade',level=10,max=10,show_uses=True,upgrade=multiple(max_hp_upgrade(5),heal_upgrade(2))),
    upgrade(texture='gold_heart',items={'dark_orb':1,'meat':50},upgrade_id='hp_4',name='Health Upgrade',level=13,max=25,show_uses=True,upgrade=multiple(max_hp_upgrade(5),heal_upgrade(5))),
    upgrade(texture='energy',items={'energy':1},upgrade_id='speed_i',name='Speed Upgrade',level=4,max=10,show_uses=True,upgrade=speed_upgrade(0.05)),
    upgrade(texture='energy',items={'energy':1,'leaf':3},upgrade_id='speed_ii',name='Speed Upgrade',level=9,max=10,show_uses=True,upgrade=speed_upgrade(0.05)),
    upgrade(texture='energy',items={'dark_orb':1},upgrade_id='speed_iii',name='Speed Upgrade',level=12,max=20,show_uses=True,upgrade=speed_upgrade(0.05)),
    upgrade(texture='xp_boost',items={'energy':1},upgrade_id='xp_i',name='XP Boost',level=11,max=10,show_uses=True,upgrade=xp_upgrade(0.1)),
    upgrade(texture='xp_boost',items={'dark_orb':1},upgrade_id='xp_ii',name='XP Boost',level=15,max=20,show_uses=True,upgrade=xp_upgrade(0.05)),
    upgrade(texture='xp_boost',items={'dark_orb':10},upgrade_id='xp_ii',name='XP Boost',level=17,max=100,show_uses=True,upgrade=xp_upgrade(0.2))
]